version: '3.8'

services:
  finance-bot:
    build: .
    container_name: finance-bot
    restart: unless-stopped
    volumes:
      - ./expenses.db:/app/expenses.db
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
